"""initial schema
Revision ID: 0001_initial
Revises:
Create Date: 2026-07-12
"""
from alembic import op
import sqlalchemy as sa
revision='0001_initial'
down_revision=None
branch_labels=None
depends_on=None
def upgrade():
    op.create_table('users', sa.Column('id',sa.Integer,primary_key=True), sa.Column('username',sa.String(80),nullable=False,unique=True), sa.Column('username_lower',sa.String(80),nullable=False,unique=True,index=True), sa.Column('password_hash',sa.String(255),nullable=False), sa.Column('role',sa.String(30),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('sessions', sa.Column('id',sa.String(64),primary_key=True), sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id'),nullable=False,index=True), sa.Column('csrf_token',sa.String(64),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False,index=True), sa.Column('rotated_from',sa.String(64),nullable=True))
    op.create_table('surf_spots', sa.Column('id',sa.Integer,primary_key=True), sa.Column('code',sa.String(20),unique=True,nullable=False), sa.Column('slug',sa.String(120),unique=True,nullable=False,index=True), sa.Column('name',sa.String(120),nullable=False), sa.Column('beach_name',sa.String(120)), sa.Column('zone_name',sa.String(160)), sa.Column('latitude',sa.Float,nullable=False), sa.Column('longitude',sa.Float,nullable=False), sa.Column('description',sa.Text), sa.Column('spot_type',sa.String(120)), sa.Column('difficulty',sa.String(160)), sa.Column('is_active_for_recommendations',sa.Boolean,nullable=False), sa.Column('preferred_swell_direction_min',sa.Float), sa.Column('preferred_swell_direction_max',sa.Float), sa.Column('acceptable_swell_direction_min',sa.Float), sa.Column('acceptable_swell_direction_max',sa.Float), sa.Column('preferred_swell_height_min',sa.Float), sa.Column('preferred_swell_height_max',sa.Float), sa.Column('maximum_safe_swell_height_for_profile',sa.Float), sa.Column('preferred_period_min',sa.Float), sa.Column('preferred_period_max',sa.Float), sa.Column('preferred_wind_direction_min',sa.Float), sa.Column('preferred_wind_direction_max',sa.Float), sa.Column('preferred_tide_min',sa.Float), sa.Column('preferred_tide_max',sa.Float), sa.Column('tide_preference',sa.String(80)), sa.Column('exposure_factor',sa.Float), sa.Column('shelter_factor',sa.Float), sa.Column('hazards',sa.Text), sa.Column('access_notes',sa.Text), sa.Column('base_confidence',sa.Float), sa.Column('webcam_url',sa.String(500)), sa.Column('seed_source_note',sa.Text), sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('provider_fetches', sa.Column('id',sa.Integer,primary_key=True), sa.Column('provider_name',sa.String(100),index=True,nullable=False), sa.Column('fetched_at',sa.DateTime(timezone=True),index=True,nullable=False), sa.Column('latitude',sa.Float), sa.Column('longitude',sa.Float), sa.Column('status',sa.String(30),nullable=False), sa.Column('raw_response',sa.JSON), sa.Column('parsing_errors',sa.Text), sa.Column('data_age_seconds',sa.Integer))
    for table in ['marine_forecasts','weather_forecasts','tide_forecasts']:
        op.create_table(table, sa.Column('id',sa.Integer,primary_key=True), sa.Column('provider_fetch_id',sa.Integer,sa.ForeignKey('provider_fetches.id')), sa.Column('provider_name',sa.String(100),index=True), sa.Column('spot_id',sa.Integer,sa.ForeignKey('surf_spots.id'),index=True), sa.Column('forecast_time',sa.DateTime(timezone=True),index=True), sa.Column('fetched_at',sa.DateTime(timezone=True),index=True), sa.Column('values',sa.JSON,nullable=False), sa.Column('provider_status',sa.String(30),nullable=False))
    op.create_table('buoy_observations', sa.Column('id',sa.Integer,primary_key=True), sa.Column('provider_name',sa.String(100)), sa.Column('station_name',sa.String(120)), sa.Column('observed_at',sa.DateTime(timezone=True),index=True), sa.Column('values',sa.JSON), sa.Column('status',sa.String(30)))
    op.create_table('spot_scores', sa.Column('id',sa.Integer,primary_key=True), sa.Column('spot_id',sa.Integer,sa.ForeignKey('surf_spots.id'),index=True), sa.Column('daypart',sa.String(20),index=True), sa.Column('score_date',sa.Date), sa.Column('score',sa.Float), sa.Column('confidence_label',sa.String(40)), sa.Column('classification',sa.String(80)), sa.Column('explanation',sa.Text), sa.Column('summary',sa.JSON), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('daily_recommendations', sa.Column('id',sa.Integer,primary_key=True), sa.Column('score_date',sa.Date,index=True), sa.Column('daypart',sa.String(20),index=True), sa.Column('spot_score_id',sa.Integer,sa.ForeignKey('spot_scores.id')), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
def downgrade():
    for t in ['daily_recommendations','spot_scores','buoy_observations','tide_forecasts','weather_forecasts','marine_forecasts','provider_fetches','surf_spots','sessions','users']:
        op.drop_table(t)
