# Initial spot parameters are provisional and intentionally centralized for field review.
SPOTS=[
 dict(code='ODE',name='Odeceixe',slug='odeceixe',zone_name='Main beach / river mouth',beach_name='Praia de Odeceixe',latitude=37.4416,longitude=-8.7977,spot_type='River-mouth beach break',difficulty='Intermediate to advanced depending on conditions',active=True,base_confidence=.70,description='Open west-coast beach with river-mouth influence and shifting sandbanks.',hazards='Currents, shifting banks, river-mouth uncertainty.',access_notes='Beach parking and walk to peaks.'),
 dict(code='AMO',name='Amoreira',slug='amoreira',zone_name='Main beach / river mouth',beach_name='Praia da Amoreira',latitude=37.3502,longitude=-8.8460,spot_type='River-mouth beach break',difficulty='Intermediate to advanced depending on conditions',active=True,base_confidence=.70,description='River-mouth beach break with multiple banks and strong tidal influence.',hazards='River currents, rocks, shifting banks.',access_notes='Access from north/south parking areas.'),
 dict(code='MCL',name='Monte Clérigo',slug='monte-clerigo',zone_name='North and central beach',beach_name='Praia de Monte Clérigo',latitude=37.3398,longitude=-8.8520,spot_type='Exposed beach break',difficulty='Intermediate to advanced',active=True,base_confidence=.76,description='Exposed beach break with relatively direct Atlantic swell exposure.',hazards='Rips, closeouts on large swell.',access_notes='Village parking near beach.'),
 dict(code='MCL-S',name='Monte Clérigo South',slug='monte-clerigo-south',zone_name='Southern rocks',beach_name='Praia de Monte Clérigo',latitude=37.3348,longitude=-8.8525,spot_type='Rock-influenced beach break',difficulty='Advanced',active=True,base_confidence=.60,description='Southern rock-influenced section requiring local assessment.',hazards='Rocks, rips, lower margin for forecast error.',access_notes='Inspect at low tide before surfing.'),
 dict(code='ARR',name='Arrifana',slug='arrifana',zone_name='Main beach',beach_name='Praia da Arrifana',latitude=37.2941,longitude=-8.8659,spot_type='Sheltered beach break',difficulty='Intermediate to advanced',active=True,base_confidence=.78,description='Sheltered bay beach break that can handle more exposed-coast energy.',hazards='Crowds, rocks near edges, rips.',access_notes='Steep road or shuttle in season.'),
 dict(code='ARR-R',name='Arrifana Reef',slug='arrifana-reef',zone_name='Reef section',beach_name='Praia da Arrifana',latitude=37.2898,longitude=-8.8694,spot_type='Reef break',difficulty='Advanced',active=True,base_confidence=.58,description='Advanced reef section requiring confidence and direct inspection.',hazards='Reef, currents, strong sets.',access_notes='Local knowledge advised.'),
 dict(code='VFI',name='Vale Figueiras',slug='vale-figueiras',zone_name='Main beach',beach_name='Praia de Vale Figueiras',latitude=37.2489,longitude=-8.8713,spot_type='Exposed beach break',difficulty='Advanced',active=True,base_confidence=.70,description='Exposed west-coast beach break with powerful surf and rips.',hazards='Powerful rips, remote feel, large-swell danger.',access_notes='Dirt road access; check conditions.'),
 dict(code='BOR-N',name='Bordeira North',slug='bordeira-north',zone_name='River mouth / northern section',beach_name='Praia da Bordeira',latitude=37.1997,longitude=-8.9039,spot_type='River-mouth beach break',difficulty='Intermediate to advanced',active=True,base_confidence=.67,description='Wide river-mouth section with shifting banks.',hazards='Longshore currents, shifting channels.',access_notes='Large beach; allow walk time.'),
 dict(code='BOR-C',name='Bordeira Central',slug='bordeira-central',zone_name='Central beach',beach_name='Praia da Bordeira',latitude=37.1964,longitude=-8.9028,spot_type='Exposed beach break',difficulty='Intermediate to advanced',active=True,base_confidence=.72,description='Expansive exposed beach break with multiple peaks.',hazards='Rips, size, wind exposure.',access_notes='Main beach access.'),
 dict(code='AMA-N',name='Amado',slug='amado',zone_name='North and main area',beach_name='Praia do Amado',latitude=37.1685,longitude=-8.9021,spot_type='Exposed beach break',difficulty='Intermediate to advanced',active=True,base_confidence=.76,description='Consistent exposed beach break with several peaks.',hazards='Crowds, rips, size on bigger swells.',access_notes='Main parking by beach.'),
 dict(code='AMA-S',name='Amado South',slug='amado-south',zone_name='Southern section',beach_name='Praia do Amado',latitude=37.1647,longitude=-8.9024,spot_type='Rock-influenced beach break',difficulty='Advanced',active=True,base_confidence=.62,description='Southern, more rock-influenced section for experienced surfers.',hazards='Rocks, currents, confidence-sensitive takeoffs.',access_notes='Inspect hazards before entry.'),
 dict(code='VDH',name='Vale dos Homens',slug='vale-dos-homens',zone_name='Main beach',beach_name='Praia de Vale dos Homens',latitude=37.3867,longitude=-8.8247,spot_type='Rocky beach break',difficulty='Advanced',active=False,base_confidence=.45,description='Advanced rocky beach break used as observation-only in prototype.',hazards='Rocks, currents, lower direct data confidence.',access_notes='Stair access; inspect carefully.'),
 dict(code='CAR',name='Carriagem',slug='carriagem',zone_name='Main beach',beach_name='Praia da Carriagem',latitude=37.3744,longitude=-8.8296,spot_type='Rocky beach break',difficulty='Advanced',active=False,base_confidence=.45,description='Rocky advanced beach setup with limited automated confidence.',hazards='Rocks, remoteness, currents.',access_notes='Tide and access awareness required.'),
 dict(code='CAN',name='Canal',slug='canal',zone_name='Reef and point area',beach_name='Praia do Canal',latitude=37.2214,longitude=-8.8773,spot_type='Reef / point break',difficulty='Advanced',active=False,base_confidence=.42,description='Advanced reef/point area retained for future observation workflows.',hazards='Reef, rocks, powerful sets, remote access.',access_notes='Use only with direct inspection/local knowledge.'),
]
DEFAULT_PARAMS=dict(preferred_swell_direction_min=285,preferred_swell_direction_max=350,acceptable_swell_direction_min=250,acceptable_swell_direction_max=30,preferred_swell_height_min=0.9,preferred_swell_height_max=2.4,maximum_safe_swell_height_for_profile=3.5,preferred_period_min=10,preferred_period_max=17,preferred_wind_direction_min=70,preferred_wind_direction_max=150,preferred_tide_min=0.25,preferred_tide_max=0.85,tide_preference='mid',exposure_factor=1.0,shelter_factor=1.0,webcam_url=None,seed_source_note='Provisional seed values and coordinates kept in app/seed_data.py for field review; no paid data used.')
USERS=[('Patrick','loliking','admin'),('Loliking','loliwave','moderator'),('David','surferking','user')]
